on:
  push:
    branches: ['**']

jobs:
  lint-test-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: sbt

      - run: sbt 'scalafixAll --check' scalafmtSbtCheck scalafmtCheck
        env:
          GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

      - run: sbt +test
        env:
          GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

      - run: sbt +publish
        env:
          GITHUB_TOKEN: ${{ secrets.WRITE_PACKAGES_TOKEN }}
          GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
