name: Continuous integration

on:
  push:
    branches: ['**']

jobs:
  lint-test-and-publish:
    name: Compile Demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - run: ./gradlew test

